AWSTemplateFormatVersion: 2010-09-09
Description: Dad jokes as a service
Parameters:
  # DynamoDB Table
  pHashKeyElementName:
    Description: HashType PrimaryKey Name
    Type: String
    AllowedPattern: "[a-zA-Z0-9]*"
    Default: "Id"
    MinLength: "1"
    MaxLength: "2048"
    ConstraintDescription: must contain only alphanumeric characters
  pHashKeyElementType:
    Description: HashType PrimaryKey Type
    Type: String
    Default: S
    AllowedPattern: "[S|N]"
    MinLength: "1"
    MaxLength: "1"
    ConstraintDescription: must be either S or N
  pJokeElementName:
    Description: Name
    Type: String
    Default: "JokeText"
    MaxLength: "2048"
  pJokeElementType:
    Description: Type
    Type: String
    Default: S
  pReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: "1"
    MinValue: "1"
    MaxValue: "5"
    ConstraintDescription: must be between 1 and 5
  pWriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: "1"
    MinValue: "1"
    MaxValue: "5"
    ConstraintDescription: must be between 1 and 5
Resources:
  rDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Dad_Jokes
      AttributeDefinitions:
        - AttributeName: !Ref pHashKeyElementName
          AttributeType: !Ref pHashKeyElementType
        - AttributeName: !Ref pJokeElementName
          AttributeType: !Ref pJokeElementType
      KeySchema:
        - AttributeName: !Ref pHashKeyElementName
          KeyType: HASH
        - AttributeName: !Ref pJokeElementName
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref pReadCapacityUnits
        WriteCapacityUnits: !Ref pWriteCapacityUnits
  rApiGatewayPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: ApiGatewayLambdaCallPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              "lambda:InvokeFunction"
              "lambda:InvokeAsync"
              "lambda:GetFunction"
        Resource:
          - !GetAtt rLambdaGetRandom.Arn
Outputs:
  ODynamoDBTable:
    Value: !Ref rDynamoDBTable
    Description: Newly created Dad Jokes DynamoDB table.
