openapi: 3.0.1
info:
  title: DadJokes-HttpApi
  version: 2023-05-12 07:50:42UTC
  description: The HTTP api gateway that handles calls for the Dad Jokes API.
paths:
  /jokes/random:
    get:
      responses:
        default:
          description: Default response for GET /jokes/random
      x-amazon-apigateway-integration:
        payloadFormatVersion: '2.0'
        type: AWS_PROXY
        httpMethod: POST
        uri: arn:aws:apigateway:ap-southeast-2:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-southeast-2:723104728616:function:Lambda-DynamoDB-DadJokes-GetRandom/invocations
        connectionType: INTERNET
x-amazon-apigateway-importexport-version: '1.0'
